length = int(input("What is the length of the room in feet? "))
width = int(input("What is the width of the room in feet? "))
print(f"You entered dimensions of {length} feet by {width} feet.\nThe area is")
print(f"{length * width} square feet")
print(f"{(length * width) * 0.09290304} square metres")